import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@/styles/globals.scss";

import { authAction } from "@/modules/auth/actions/auth";
import { Footer } from "@/modules/shared/components/navigation/footer";
import { Header } from "@/modules/shared/components/navigation/header";
import { UserProvider } from "@/modules/user/context/provider/user-context-provider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const response = await authAction();

	if (!response.success) {
		console.log(response.message);
	}

	return (
		<UserProvider user={response.user}>
			<html lang="en">
				<body className={`${geistSans.variable} ${geistMono.variable}`}>
					<Header />
					{children}
					<Footer />
				</body>
			</html>
		</UserProvider>
	);
}
